name: AddOssIndexExclusion
on:
  workflow_dispatch:
    inputs:
      # qlty-ignore: checkov:CKV_GHA_7
      exclusion:
        description: "Vulnerability to exclude"
        required: true
        type: string

permissions: read-all

jobs:
  build:
    name: Add OSS Index Exclusion action
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Add exclusion
        run: |
          echo "${{ github.event.inputs.exclusion }}" >> config/ossindex/exclusions.txt
      - name: Create git branch
        run: |
          git config --global user.name 'Esta Nagy'
          git config --global user.email 'nagyesta@gmail.com'
          git checkout -b feature/exclude-vulnerability-run-${{ github.run_number }}
          git add config/ossindex/exclusions.txt
          git commit -asm "Excluding vulnerability ${{ github.event.inputs.exclusion }} {patch}"
          git push -f --set-upstream origin feature/exclude-vulnerability-run-${{ github.run_number }}
      - name: Create PR
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "feature/exclude-vulnerability-run-${{ github.run_number }}",
              base: "main",
              title: "Excluding vulnerability ${{ github.event.inputs.exclusion }} {patch}"
            });
