name: AddOssIndexExclusion
on:
  workflow_dispatch:
    inputs:
      # qlty-ignore: checkov:CKV_GHA_7
      exclusion:
        description: "Vulnerability to exclude"
        required: true
        type: string

permissions: read-all

jobs:
  build:
    name: Add OSS Index Exclusion action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_KEY }}
      - name: Add exclusion
        run: |
          echo "${{ github.event.inputs.exclusion }}" >> config/ossindex/exclusions.txt
      - name: Create git branch
        run: |
          git config --global user.name 'Esta Nagy'
          git config --global user.email 'nagyesta@gmail.com'
          git checkout -b feature/exclude-vulnerability-run-${{ github.run_number }}
          git add config/ossindex/exclusions.txt
          git commit -asm "Excluding vulnerability ${{ github.event.inputs.exclusion }} {patch}"
          git push -f --set-upstream origin feature/exclude-vulnerability-run-${{ github.run_number }}
      - name: Create PR
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.PUBLISH_KEY }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "feature/exclude-vulnerability-run-${{ github.run_number }}",
              base: "main",
              title: "Excluding vulnerability ${{ github.event.inputs.exclusion }} {patch}"
            });
